project:
  type: website
  render:
    - "*.qmd"
    - "!more_figures_n_checks.qmd"
    - "!26z*.qmd"

website:
  title: "MIP"
  navbar:
    left:
      - blog.qmd
      # - about.qmd
      # - text: Cars
      #   href: posts/other-notebook.ipynb
      # - text: Analysis
      #   href: posts/hello-penguins.ipynb

# format:
#   html:
#     toc: true
#     theme: lux